### PR TITLE
ENH PHP 8.1 compatibility

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/silverstripe-framework/issues/10250

### CODE REVIEW

**Review by tractorcow — APPROVED** [review]

**Review by GuySartorelli — APPROVED** [review]
For posterity: See discussion in silverstripe/silverstripe-admin#1294 about the general approach. tl;dr:
> the purposes of this PR is to avoid passing null (specifically null) from built-in functions that as of php 8.1 will throw deprecation warnings if null is passed in. The approach is necessarily heavy-handed, and while there are many situations where it isn't needed, it would be prohibitively laborious to find all of those situations by hand.

Looks good to me, though I don't have access to merge this one.

**Comment by tractorcow** [comment]
I've tagged 1.0.0 fyi

**Comment by emteknetnz** [comment]
@tractorcow any chance you could tag 0.1.3? - proxy-db requires ^0.1.1 https://github.com/tractorcow/silverstripe-proxy-db/blob/master/composer.json

**Comment by emteknetnz** [comment]
@tractorcow I've opened up a subsequent [pull-request](https://github.com/tractorcow/silverstripe-proxy-db/pull/3) on proxy-db to require ^1 of classproxy

**Pull request merged**
